<script setup>
import { ref } from 'vue';
import { useAuthStore } from '@/stores/auth.store';
import ProjectsView from './ProjectsView.vue';
import AuthModal from '@/components/AuthModal.vue';

const authStore = useAuthStore();
const isAuthModalVisible = ref(false);
const authModalMode = ref('login'); // 'login' or 'register'

const showAuthModal = (mode) => {
  authModalMode.value = mode;
  isAuthModalVisible.value = true;
};

const closeAuthModal = () => {
  isAuthModalVisible.value = false;
};

const onAuthSuccess = () => {
  // Có thể làm mới dữ liệu hoặc chuyển hướng tại đây
  console.log("Xác thực thành công!");
  closeAuthModal();
}
</script>

<template>
  <!-- Đảm bảo font Inter được tải -->
  <Teleport to="head">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
      rel="stylesheet">
  </Teleport>

  <!-- Lớp bọc chính với nền gradient tinh tế -->
  <div class="page-wrapper">
    <!-- Header với hiệu ứng Glassmorphism trên nền sáng -->
    <header class="navbar">
      <div class="navbar-brand">
        <!-- Thay thế bằng URL logo của bạn -->
        <img src="@/assets/techsage_logo.png" alt="TechSage Logo" class="logo-img bounce-top" />
        <h1>TechSage</h1>
      </div>
      <nav class="navbar-settings">
        <div v-if="!authStore.isLoggedIn" class="auth-links">
          <button @click="showAuthModal('login')" class="nav-button">Login</button>
          <button @click="showAuthModal('register')" class="nav-button primary">Register</button>
        </div>
        <div v-else>
          <!-- Nút Logout được tạo kiểu nhất quán -->
          <button @click="authStore.logout" class="nav-button">Logout</button>
        </div>
      </nav>
    </header>

    <!-- Nội dung chính -->
    <main class="container">
      <ProjectsView />
    </main>

    <!-- Nút hành động nổi (FAB) được thiết kế lại -->
    <div class="fab-menu">
      <button class="fab-button">+</button>
    </div>
  </div>

  <Teleport to="body">
    <AuthModal v-if="isAuthModalVisible" :initial-mode="authModalMode" @close="closeAuthModal"
      @authSuccess="onAuthSuccess" />
  </Teleport>
</template>

<style scoped>
/* Thiết lập font chữ và nền cơ bản */
.page-wrapper {
  font-family: 'Inter', sans-serif;
  background-color: #f4f7f6;
  /* Thêm các dải màu gradient nhẹ ở góc để tạo chiều sâu */
  background-image:
    radial-gradient(at 0% 0%, hsla(148, 70%, 85%, 0.4) 0px, transparent 50%),
    radial-gradient(at 98% 99%, hsla(170, 70%, 80%, 0.4) 0px, transparent 50%);
  min-height: 100vh;
  position: relative;
  display: flex;
  flex-direction: column;
}

/* Header (Navbar) với hiệu ứng Liquid Glass trên nền sáng */
.navbar {
  position: sticky;
  top: 0px;
  left: 0px;
  width: 100%;
  padding: 1rem 10rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  z-index: 10;
  border-radius: 12px;
  /* Bo tròn các góc */

  /* Hiệu ứng Glassmorphism */
  background: rgba(255, 255, 255, 0.6);
  backdrop-filter: blur(10px) saturate(180%);
  -webkit-backdrop-filter: blur(10px) saturate(180%);
  border: 1px solid rgba(31, 41, 55, 0.1);
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.07);
}

.navbar-brand {
  display: flex;
  align-items: center;
  gap: 12px;
}

.logo-img {
  height: 36px;
  width: 36px;
  object-fit: contain;
}

.navbar-brand h1 {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1f2937;
  /* Màu văn bản tối để dễ đọc trên nền sáng */
  letter-spacing: -0.02em;
  margin: 0;
}

/* Các nút điều hướng */
.navbar-settings .auth-links {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.nav-button {
  font-family: 'Inter', sans-serif;
  font-size: 0.95rem;
  font-weight: 500;
  color: #4b5563;
  /* Màu văn bản phụ */
  background: transparent;
  border: none;
  padding: 8px 16px;
  border-radius: 8px;
  cursor: pointer;
  text-decoration: none;
  transition: all 0.3s ease;
}

.nav-button:hover {
  background: rgba(31, 41, 55, 0.05);
  color: #1f2937;
}

.nav-button.primary {
  background-color: #34d399;
  border-color: #34d399;
  color: #ffffff;
  font-weight: 600;
}

.nav-button.primary:hover {
  background-color: #2bb989;
  transform: translateY(-2px);
  box-shadow: 0 4px 15px rgba(52, 211, 153, 0.25);
}

.bounce-top {
  -webkit-animation: bounce-top 0.9s both;
  animation: bounce-top 0.9s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-7-13 23:4:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-top
 * ----------------------------------------
 */
@-webkit-keyframes bounce-top {
  0% {
    -webkit-transform: translateY(-45px);
    transform: translateY(-45px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 1;
  }

  24% {
    opacity: 1;
  }

  40% {
    -webkit-transform: translateY(-24px);
    transform: translateY(-24px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  65% {
    -webkit-transform: translateY(-12px);
    transform: translateY(-12px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  82% {
    -webkit-transform: translateY(-6px);
    transform: translateY(-6px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  93% {
    -webkit-transform: translateY(-4px);
    transform: translateY(-4px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  25%,
  55%,
  75%,
  87% {
    -webkit-transform: translateY(0px);
    transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }

  100% {
    -webkit-transform: translateY(0px);
    transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
}

@keyframes bounce-top {
  0% {
    -webkit-transform: translateY(-45px);
    transform: translateY(-45px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
    opacity: 1;
  }

  24% {
    opacity: 1;
  }

  40% {
    -webkit-transform: translateY(-24px);
    transform: translateY(-24px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  65% {
    -webkit-transform: translateY(-12px);
    transform: translateY(-12px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  82% {
    -webkit-transform: translateY(-6px);
    transform: translateY(-6px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  93% {
    -webkit-transform: translateY(-4px);
    transform: translateY(-4px);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }

  25%,
  55%,
  75%,
  87% {
    -webkit-transform: translateY(0px);
    transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }

  100% {
    -webkit-transform: translateY(0px);
    transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    opacity: 1;
  }
}

/* Container nội dung chính */
.container {
  width: 100%;
  max-width: 1200px;
  margin: 2rem auto;
  padding: 0 5%;
  box-sizing: border-box;
  flex-grow: 1;
  z-index: 5;
}

/* Nút hành động nổi (FAB) */
.fab-menu {
  position: fixed;
  bottom: 2rem;
  right: 2rem;
  z-index: 999;
}

.fab-button {
  background: linear-gradient(45deg, #34d399, #2dd4bf);
  color: #ffffff;
  border: none;
  border-radius: 50%;
  width: 60px;
  height: 60px;
  font-size: 2rem;
  font-weight: 400;
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  box-shadow: 0 8px 25px rgba(52, 211, 153, 0.3);
  transition: all 0.3s ease-in-out;
}

.fab-button:hover {
  transform: translateY(-4px) scale(1.05);
  box-shadow: 0 12px 30px rgba(45, 212, 191, 0.4);
}

/* Responsive Design */
@media (max-width: 768px) {
  .navbar {
    width: 95%;
    padding: 0.75rem 1rem;
    top: 10px;
  }

  .navbar-brand h1 {
    font-size: 1.25rem;
  }

  .nav-button {
    padding: 6px 10px;
    font-size: 0.9rem;
  }

  .fab-menu {
    bottom: 1.5rem;
    right: 1.5rem;
  }

  .fab-button {
    width: 54px;
    height: 54px;
    font-size: 1.8rem;
  }
}

@media (max-width: 480px) {
  .navbar-brand h1 {
    display: none;
    /* Ẩn chữ trên màn hình nhỏ, chỉ giữ lại logo */
  }
}
</style>
